services:
  - type: web
    name: pet-care-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: petcare-db
          property: connectionString
    plan: free

databases:
  - name: petcare-db
    databaseName: petcare
    user: petcare_user
    plan: free
